services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
     - mariadb
    restart: always
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    depends_on:
      - wordpress
      - adminer
    restart: always
      
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
        - 8080:8080
    restart: always
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    env_file: .env
    networks:
      - inception
    ports:
      - 21:21
    restart: always


networks:
  inception:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aes-sayo/data/mysql

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aes-sayo/data/wordpress

