services:
  
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
     - mariadb
     - redis
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    depends_on:
      - wordpress
      - mariadb
    restart: always
      
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb
    restart: always

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  static_website:
    build: ./requirements/bonus/static_website
    image: static_website
    container_name: static_website
    depends_on:
      - mariadb
    env_file: .env
    ports:
      - 6789:6789
    networks:
      - inception
    restart: always

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    env_file: .env
    ports:
      - 20:20
      - 21:21
      - "30000-30010:30000-30010"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

    networks:
      - inception
    restart: always
  
  redis_commander:
    build: ./requirements/bonus/redis_commander
    image: redis_commander
    container_name: redis_commander
    env_file: .env
    ports:
      - 8081:8081
    networks:
      - inception
    depends_on:
      - redis
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aes-sayo/data/mysql
  
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aes-sayo/data/wordpress

